name: 🛡️ Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: '0.65.0'

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: myapp:latest
          load: true

      - name: Scan Docker image
        run: |
          trivy image \
            --exit-code 1 \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            --scanners vuln \
            --format table \
            --cache-dir ~/.cache/trivy \
            myapp:latest
