name: 🛡️ Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ hashFiles('**/requirements.txt', '**/Dockerfile') }}
          restore-keys: trivy-db-

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: myapp:latest
          load: true
          push: false

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: myapp:latest
          exit-code: '1'
          ignore-unfixed: true
          scanners: vuln
          severity: CRITICAL,HIGH
          format: sarif
          output: trivy-results.sarif
          cache-dir: ~/.cache/trivy

      - name: Upload Trivy scan results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
