name: Trivy Image Scan

on: [push]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.65.0/trivy_0.65.0_Linux-64bit.tar.gz
          tar -xzf trivy_0.65.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Scan Docker Image
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH myapp:latest
