name: 🛡️ Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-trivy-db-

      - name: Install Trivy and scan for vulnerabilities
        uses: aquasecurity/trivy-action@0.13
        with:
          version: '0.65.0'
          scan-type: 'image'
          image-ref: 'myapp:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'
          cache-dir: '~/.cache/trivy'
