name: 🛡️ Trivy Security Scan

on: [push, pull_request]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          trivy-version: '0.65.0'

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Scan Docker Image
        run: |
          trivy image \
            --exit-code 1 \
            --severity CRITICAL \
            --ignore-unfixed \
            --security-checks vuln \
            --format table \
            --ignorefile .trivyignore \
            myapp:latest
