name: Trivy Scan on macOS

on: [push]

jobs:
  trivy-scan:
    runs-on: macos-latest  # or macos-14 (Sonoma)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: brew install trivy  # Simplest method for macOS

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Scan Docker Image
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH myapp:latest
