name: 🔒 AUCA Container Security

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Build Docker image
        run: docker build -t auca-app .

      - name: Scan for Critical/High vulnerabilities
        run: |
          trivy image \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --format table \
            auca-app

      - name: Upload Full Report
        if: always()
        run: |
          trivy image --format json --output trivy-results.json auca-app
        continue-on-error: true
