name: 🛡️ AUCA Trivy Security Scan

on: [push]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.9.0
        with:
          version: 'latest'

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Scan with Trivy
        run: |
          trivy image \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --ignore-unfixed \
            --format table \
            myapp:latest
